excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://taylorbf.github.io
title: eval
email: taylorbf@gmail.com
author: Ben Taylor
description: ____
paginate: 3
google_analytics: 